// <auto-generated />
namespace T1809E.COINMARKET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addThumbnailForPost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addThumbnailForPost));
        
        string IMigrationMetadata.Id
        {
            get { return "202006061421135_addThumbnailForPost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
